[build]
  base = "shankly-schedule"
  command = "npm install && npm run build"
  publish = "shankly-schedule/dist"
  functions = "shankly-schedule/netlify/functions"

[build.environment]
  NODE_VERSION = "18"
